### ISSUE TITLE
Libraries Unet2d not exits

### ISSUE THREAD

**Issue by bryt888** [tcapelle/cloud_diffusion#3]
when I run "python inference.py  --future_frames 10 --num_random_experiments 2", it shows "UNet2D" not in ddpm library.
the following line cause problem.
'from cloud_diffusion.ddpm import UNet2D, get_unet_params, ddim_sampler'

I noticed there is Unet2D class in cloud_diffusion.models, I changed to the following two lines. 
'from cloud_diffusion.models import UNet2D, get_unet_params'
'from cloud_diffusion.ddpm import ddim_sampler'

the code will run, but shows another error: 
"self.__class__.__name__, "\n\t".join(error_msgs)))
runtimeerror: Error(s) in loading state_dict for UNet2D:
missing keys in State_dict:"Down_blocks.1......

should I import Unet2D from models or somewhere else?
thanks!

**Comment by tcapelle** [comment]
Fixed it, pinned down to the exact library versions. Sorry for that.

**Comment by bryt888** [comment]
I will try it later.
Really appreciate your great work!

Tommy
