### ISSUE TITLE
I didn't see the content of the photovoltaic power generation forecast

### ISSUE THREAD

**Issue by liujian123223** [tcapelle/cloud_diffusion#4]
Thank you very much for providing such excellent work, which has inspired me a lot, but I still have two questions that I hope you can answer.

1. Is there a corresponding paper to read for this job? I hope to learn more details.
2. In this work, I only saw the content of predicting future cloud motion images and did not see how to use the predicted images for photovoltaic power generation prediction. Where can I find this part of the content?
3. What graphics card is needed to run your job? My name is nvidia4060. Can I run it?

Looking forward to your reply！

**Comment by tcapelle** [comment]
Better, there is a video: https://wandb.ai/capecape/ddpm_clouds/reports/GTC-Diffusion-on-the-Clouds--VmlldzozNzQ1OTkz
